# Generated by Django 4.2 on 2023-04-11 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='mame',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='mame',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='user.language'),
        ),
    ]
